### Create new Product 01
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "안녕하세요2",
  "price": 10,
  "stock": 5
}

### Modify Product 01
PUT http://localhost:8080/api/products/1
Content-Type: application/json

{
  "price": 5
}

### Decrease stock of Product 01
PATCH http://localhost:8080/api/products/1/decrease-stock?quantity=1

### Create new Product 01 again
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "product01",
  "price": 1000,
  "stock": 10
}

### Change ProductService logger level
POST http://localhost:8080/actuator/loggers/codeit.sb06.reliability.service.ProductService
Content-Type: application/json

{
  "configuredLevel": "DEBUG"
}